project:
  type: website
  output-dir: docs

website:
  title: "SANG-IL LEE"
  favicon: me.png
  google-analytics: "G-SVCM6WKTWH"
  navbar:
    # logo: images/snu_geog_2.png
    left:
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: works.qmd
      - text: "Classes"
        href: lectures.qmd
      - text: "R Development"
        href: r_dev.qmd
      - text: "R Web Books"
        href: r_web_book.qmd
      - text: "R Packages"
        href: r_packages.qmd
      - text: "Talks"
        href: talks.qmd
      - text: "Events"
        href: events.qmd      
      - text: "Blog"
        href: blog.qmd

  back-to-top-navigation: true
  page-navigation: true
  page-footer: 
    left: "Copyright 2026, Sang-Il Lee"
    border: true
  repo-url: https://github.com/sangillee66/sangillee66.github.io
  repo-actions: [issue]

format:
  html:
    theme: 
      light: [flatly, custom_basic_pretendard.scss]
      dark: [darkly, custom_basic_pretendard.scss]
    css: styles.css
    toc: true

execute:
  freeze: auto
  
editor: visual

lightbox: true
